// tree_walker_unified.v
// Parallel tree walker for Random Forest (up to 255 trees, up to 127 nodes per tree)
// Uses unified BRAM arrays: unified_node_feature, unified_node_threshold, unified_node_left,
// unified_node_right, unified_node_leaf_class. These arrays are initialized via $readmemh
// from files generated by export_model_to_bram.py

module tree_walker_unified #(
    parameter NUM_TREES = 30,
    parameter MAX_NODES_PER_TREE = 127,
    parameter TOTAL_NODES = NUM_TREES * MAX_NODES_PER_TREE,
    parameter FEATURE_WIDTH = 16        // Q10.5 fixed-point
)(
    input wire clk,
    input wire rst,
    input wire enable,                  // from FSM
    input wire [FEATURE_WIDTH-1:0] features [0:16], // 17 features
    input wire [4:0] ml_threshold,      // majority threshold (from AXI register)
    output reg attack_detected,
    output reg [7:0] vote_count         // up to 255 trees
);

    // Include the unified BRAM arrays and their initialization
    `include "tree_nodes_unified.vh"

    // Tree walker state for each tree (parallel)
    genvar t;
    generate
        for (t = 0; t < NUM_TREES; t = t + 1) begin : tree_walkers
            reg [6:0] cur_node;          // current node index (0..MAX_NODES_PER_TREE-1)
            reg [6:0] next_node;
            reg [7:0] result;            // 0 = benign, 1 = attack, 2 = still walking
            reg walking;
            reg [$clog2(MAX_DEPTH)-1:0] step; // optional depth counter

            always @(posedge clk or posedge rst) begin
                if (rst) begin
                    cur_node <= 0;
                    walking <= 0;
                    result <= 0;
                end else if (enable) begin
                    if (!walking) begin
                        // start walking the tree from root
                        cur_node <= 0;
                        walking <= 1;
                        result <= 2; // walking
                    end else begin
                        // traverse one node per clock
                        if (unified_node_leaf_class[t * MAX_NODES_PER_TREE + cur_node] != 8'hFF) begin
                            // leaf node
                            result <= unified_node_leaf_class[t * MAX_NODES_PER_TREE + cur_node] & 1;
                            walking <= 0;
                        end else begin
                            // internal node: compare feature with threshold
                            if (features[unified_node_feature[t * MAX_NODES_PER_TREE + cur_node]] <=
                                $signed(unified_node_threshold[t * MAX_NODES_PER_TREE + cur_node]))
                                cur_node <= unified_node_left[t * MAX_NODES_PER_TREE + cur_node];
                            else
                                cur_node <= unified_node_right[t * MAX_NODES_PER_TREE + cur_node];
                        end
                    end
                end else begin
                    walking <= 0;
                end
            end

            assign tree_walkers[t].vote = (result == 1) ? 1 : 0;
        end
    endgenerate

    // Count votes (combinational, all trees produce result after enough clocks)
    integer i;
    reg [7:0] vote_cnt;

    always @(*) begin
        vote_cnt = 0;
        for (i = 0; i < NUM_TREES; i = i + 1) begin
            if (tree_walkers[i].result == 1)
                vote_cnt = vote_cnt + 1;
        end
        vote_count = vote_cnt;
        attack_detected = (vote_cnt > ml_threshold);
    end

endmodule
